version: 0.1
author: ov3rk1ll
name: NamedSignEdit
main: com.ov3rk1ll.nse.NamedSignEditPlugin

commands:
 nse:
  description: Remotely edit signs.
  usage: nse <name|set|clear> <signname> ...
 namedsignedit:
  description: Remotely edit signs.
  usage: namesignedit <name|set|clear> <signname> ...
 nhe:
  description: Remotely edit player heads.
  usage: nhe <name|set|clear> <headname> ...
 namedheadedit:
  description: Remotely edit player heads.
  usage: nameheadedit <name|set|clear> <headname> ...